package game

const BATTLE_POSITIONS_SIZE = 2
const BATTLE_TEAM_CAPACITY = 6
const BATTLE_TEAM_SIZE = 4
const CLIENT_LOG_SIZE = 30
const SERVER_LOG_RETENTION_SIZE = 300

const FOCUS_UP_COEF = 1.1
const FOCUS_DOWN_COEF = 0.91
const BASE_IV = 32
const LV_100_XP = 1000000

const NATURE_WEAKNESS_FULL = 2
const NATURE_WEAKNESS_PARTIAL = 1.25
const NATURE_RESISTANCE_PARTIAL = 0.8
const NATURE_RESISTANCE_FULL = 0.5

const STAMINA_RECOVERY = 0.08
