/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpRouteImport } from './routes/up'
import { Route as TeamBuilderRouteImport } from './routes/team-builder'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as IndexRouteImport } from './routes/index'

const UpRoute = UpRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamBuilderRoute = TeamBuilderRouteImport.update({
  id: '/team-builder',
  path: '/team-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/debug': typeof DebugRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/team-builder': typeof TeamBuilderRoute
  '/up': typeof UpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/debug': typeof DebugRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/team-builder': typeof TeamBuilderRoute
  '/up': typeof UpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/debug': typeof DebugRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/team-builder': typeof TeamBuilderRoute
  '/up': typeof UpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battle'
    | '/debug'
    | '/lobby'
    | '/login'
    | '/team-builder'
    | '/up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/battle' | '/debug' | '/lobby' | '/login' | '/team-builder' | '/up'
  id:
    | '__root__'
    | '/'
    | '/battle'
    | '/debug'
    | '/lobby'
    | '/login'
    | '/team-builder'
    | '/up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleRoute: typeof BattleRoute
  DebugRoute: typeof DebugRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  TeamBuilderRoute: typeof TeamBuilderRoute
  UpRoute: typeof UpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/up': {
      id: '/up'
      path: '/up'
      fullPath: '/up'
      preLoaderRoute: typeof UpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-builder': {
      id: '/team-builder'
      path: '/team-builder'
      fullPath: '/team-builder'
      preLoaderRoute: typeof TeamBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleRoute: BattleRoute,
  DebugRoute: DebugRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  TeamBuilderRoute: TeamBuilderRoute,
  UpRoute: UpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
