// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (user_id, team_config)
VALUES ($1, $2)
RETURNING id, user_id, team_config, created_at
`

type CreateTeamParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	TeamConfig TeamConfig `json:"team_config"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.UserID, arg.TeamConfig)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamConfig,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT
    id,
    user_id,
    COALESCE(team_config, '{}'::jsonb) AS team_config,
    created_at
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamsByUser = `-- name: GetTeamsByUser :many
SELECT
    id,
    user_id,
    COALESCE(team_config, '{}'::jsonb) AS team_config,
    created_at
FROM teams
WHERE user_id = $1
`

func (q *Queries) GetTeamsByUser(ctx context.Context, userID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeamsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TeamConfig,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET team_config = $2
WHERE id = $1
RETURNING id, user_id, team_config, created_at
`

type UpdateTeamParams struct {
	ID         uuid.UUID  `json:"id"`
	TeamConfig TeamConfig `json:"team_config"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.ID, arg.TeamConfig)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamConfig,
		&i.CreatedAt,
	)
	return i, err
}
